version: "3.2"
services:
  release-tracker:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_HOST: database
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: neon-releasetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
